services:

   # Событие настройки сопоставления сущности.
   Maris\Symfony\Address\EventListener\PreMappingListener:
      arguments:
         $mappingExclude: '%address.model.exclude%'

      tags:
         -
            name: 'doctrine.event_listener'
            event: 'loadClassMetadata'

